---
- name: CREATE AND EXECUTE SCRIPTS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: CREATE SCRIPT
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "TestScript"
        script_type: "cli"
        script_target: "FG1"
        script_description: "Create by Ansible"
        script_content: "get system status"

    - name: EXECUTE SCRIPT
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "TestScript"
        state: "execute"
        script_scope: "FGT1"
    #- name: DELETE SCRIPT
    #  fmgr_script:
    #    host: "{{ inventory_hostname }}"
    #    username: "{{ username }}"
    #    password: "{{ password }}"
    #    adom: "ansible"
    #    script_name: ""
    #    state: "delete"
