---

- name: CONFIG IPv4 IP ADDRESS OBJECT
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  - name: ADD MULTICAST RANGE
    fmgr_fwobj_address:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      adom: "ansible"
      mode: "add"
      multicast: "multicastrange"
      start_ip: "224.0.0.251"
      end_ip: "224.0.0.251"
      name: "ansible_multicastrange"
      comment: "Dev by Ansible"
      color: "22"
      tags: "blahBlahBlah"
