---

- name: CONFIG FMGR FIREWALL OBJECTS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  - name: ADD IPv4 IP ADDRESS GEO OBJECT
    fmgr_fwobj_address:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ipv4: "geography"
      country: "US"
      mode: "add"
      adom: "ansible"
      name: "ansible_geo"
      comment: "Dev Example for Ansible"
      color: "22"
      tags: "ipv4, test123, test321"