---

- name: CONFIG FMGR FIREWALL OBJECTS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  - name: ADD IPv4 IP ADDRESS FQDN OBJECT
    fmgr_fwobj_address:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ipv4: "fqdn"
      mode: "add"
      adom: "ansible"
      fqdn: "bluesnews.com"
      name: "Bluesnews"
      comment: "Dev Example for Ansible"
      color: "22"
      tags: "ansible, ipv4, test123, test321"
