---

- name: CONFIG FMGR FIREWALL OBJECTS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  - name: ADD IPv4 IP ADDRESS WILDCARD OBJECT
    fmgr_fwobj_address:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      mode: "add"
      adom: "ansible"
      ipv4: "wildcard"
      wildcard: "10.7.220.0/24"
      name: "ansible_v4Obj_wildCard"
      comment: "Dev Example for Ansible"
      color: "22"
      tags: "ansible, ipv4, test123, test321"
