var_fgt_ha_scripts:
  - adom: "ansible"
    script_name: "fgt_ha_group10"
    script_type: "cli"
    script_target: "remote_device"
    script_description: "HA SCRIPT FOR fgt-cluster01"
    script_content: "config route static \n
                      purge \n
                      y \n
                      end \n
                     config system ha \n
                      set group-id 10 \n
                      set group-name 'fgt-cluster' \n
                      set mode a-p \n
                      set password fortinet \n
                      set priority 200 \n
                      set hbdev port10 200 port9 100 \n
                      set authentication enable \n
                      set session-pickup enable \n
                      set session-pickup-connectionless enable \n
                      set override disable \n
                      set ha-mgmt-status enable \n
                      config ha-mgmt-interfaces \n
                        edit 1 \n
                          set interface port1 \n
                          set gateway 10.7.220.254 \n
                          set dst 0.0.0.0/0 \n
                          end \n
                      end \n
                      execute update-now \n"