var_fgt_intf_provision:
# FGT 01
  - device_unique_name: "seattle-fgt01"
    adom: "ansible"
    interface: "port10"
    interface_ip: "192.168.110.1/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "seattle-fgt01"
    adom: "ansible"
    interface: "port9"
    interface_ip: "192.168.109.1/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "seattle-fgt01"
    adom: "ansible"
    interface: "port8"
    interface_ip: "10.7.221.81/24"
    interface_allow_access: "https, ping, fgfm"
# FGT02
  - device_unique_name: "seattle-fgt02"
    adom: "ansible"
    interface: "port10"
    interface_ip: "192.168.110.2/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "seattle-fgt02"
    adom: "ansible"
    interface: "port9"
    interface_ip: "192.168.109.2/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "seattle-fgt02"
    adom: "ansible"
    interface: "port8"
    interface_ip: "10.7.221.82/24"
    interface_allow_access: "https, ping, fgfm"
# FGT 03
  - device_unique_name: "seattle-fgt03"
    adom: "ansible"
    interface: "port10"
    interface_ip: "192.168.110.3/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "seattle-fgt03"
    adom: "ansible"
    interface: "port9"
    interface_ip: "192.168.109.3/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "seattle-fgt03"
    adom: "ansible"
    interface: "port8"
    interface_ip: "10.7.221.83/24"
    interface_allow_access: "https, ping, fgfm"
# FGT 04
  - device_unique_name: "nyc-fgt01"
    adom: "ansible"
    interface: "port10"
    interface_ip: "192.168.110.4/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "nyc-fgt01"
    adom: "ansible"
    interface: "port9"
    interface_ip: "192.168.109.4/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "nyc-fgt01"
    adom: "ansible"
    interface: "port8"
    interface_ip: "10.7.221.91/25"
    interface_allow_access: "https, ping, fgfm"
# FGT 05
  - device_unique_name: "nyc-fgt02"
    adom: "ansible"
    interface: "port10"
    interface_ip: "192.168.110.5/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "nyc-fgt02"
    adom: "ansible"
    interface: "port9"
    interface_ip: "192.168.109.5/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "nyc-fgt02"
    adom: "ansible"
    interface: "port8"
    interface_ip: "10.7.221.92/24"
    interface_allow_access: "https, ping, fgfm"
# FGT 06
  - device_unique_name: "nyc-fgt03"
    adom: "ansible"
    interface: "port10"
    interface_ip: "192.168.110.6/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "nyc-fgt03"
    adom: "ansible"
    interface: "port9"
    interface_ip: "192.168.109.6/24"
    interface_allow_access: "https, ping"
  - device_unique_name: "nyc-fgt03"
    adom: "ansible"
    interface: "port8"
    interface_ip: "10.7.221.93/24"
    interface_allow_access: "https, ping, fgfm"
