---

- name: SET FORTIMANAGER HA MODE TO STANDALONE
  hosts: FortiManager, FortiManagerSlave
  connection: local
  gather_facts: False

  tasks:

  - name: SET FORTIMANAGER HA NODE TO STANDALONE
    fmgr_ha:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      fmgr_ha_mode: "standalone"