---
- name: ADD FMG HA PEER
  hosts: FortiManagerSlave
  connection: local
  gather_facts: False

  tasks:
    - name: ADD FORTIMANAGER HA PEER
      fmgr_ha:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fmgr_ha_peer_ipv4: "10.7.220.35"
        fmgr_ha_peer_sn: "FMG-VM0A17004505"
        fmgr_ha_peer_status: "enable"
        fmgr_ha_mode: "slave"
        fmgr_ha_cluster_pw: "fortinet"
        fmgr_ha_cluster_id: "2"
