---

- name: CONFIG CUSTOM SERVICES
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  # BASIC FULL PORT NAT MAPPING
  - name: DELETE FMGR_FIREWALL_VIP PNAT
    fmgr_fwobj_vip:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "Basic PNAT Map Port 10443"
      mode: "delete"
      adom: "ansible"

  - name: DELETE FMGR_FIREWALL_VIP SNAT
    fmgr_fwobj_vip:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "Basic StaticNAT Map"
      mode: "delete"
      adom: "ansible"

  - name: DELETE FMGR_FIREWALL_VIP DNS
    fmgr_fwobj_vip:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "Basic DNS Translation"
      mode: "delete"
      adom: "ansible"

  - name: DELETE FMGR_FIREWALL_VIP FQDN
    fmgr_fwobj_vip:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "Basic FQDN Translation"
      mode: "delete"
      adom: "ansible"



