---
- name: CONFIGURE 3 FORTIGATES FROM SCRATCH INTO HA CLUSTER
  hosts: FortiManager
  connection: local
  gather_facts: False
  vars_files:
    - var_fgts_to_provision.yml
    - var_fgt_intf_to_provision.yml
    - var_fgt_clusters.yml
    - var_fgt_ha_scripts.yml

  tasks:
    - name: DISCOVER AND ADD DEVICES VIA LOOP
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_username: "{{ item.device_username }}"
        device_password: "{{ item.device_password }}"
        device_ip: "{{ item.device_ip }}"
        device_unique_name: "{{ item.device_unique_name }}"
      tags:
        - discover
      with_items: "{{ var_fgts_to_provision }}"

    - name: CHANGE HOSTNAMES VIA LOOP
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        device_hostname: "{{ item.device_hostname }}"
        device_unique_name: "{{ item.device_unique_name }}"
        adom: "{{ item.adom }}"
      tags:
        - hostname
      with_items: "{{ var_fgts_to_provision }}"

    - name: EDIT INTERFACE INFORMATION ON FORTIGATES
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_unique_name: "{{ item.device_unique_name }}"
        interface: "{{ item.interface }}"
        interface_ip: "{{ item.interface_ip }}"
        interface_allow_access: "{{ item.interface_allow_access }}"
      tags:
        - interface
      with_items: "{{ var_fgt_intf_provision }}"

    - name: INSTALL NEW CONFIGS TO FORTIGATES
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_unique_name: "{{ item.device_unique_name }}"
        install_config: "enable"
      tags:
        - config_install
      with_items: "{{ var_fgts_to_provision }}"

    - pause:
        seconds: 30

    - name: CREATE SCRIPT FOR CLUSTER INIT
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        script_name: "{{ item.script_name }}"
        script_type: "{{ item.script_type }}"
        script_target: "{{ item.script_target }}"
        script_description: "{{ item.script_description }}"
        script_content: "{{ item.script_content }}"
      tags:
        - create_script
      with_items: "{{ var_fgt_ha_scripts }}"

    - name: EXECUTE SCRIPT ON FORTIGATES
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        script_name: "{{ item.script_name }}"
        state: "execute"
        script_scope: "{{ item.device_unique_name }}"
      tags:
        - exec_script
      with_items: "{{ var_fgts_to_provision }}"

    - pause:
        seconds: 60

    - name: DELETE SINGLE FORTIGATES FROM FORTIMANAGER
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_unique_name: "{{ item.device_unique_name }}"
        state: "absent"
      tags:
        - delete_fgts
      with_items: "{{ var_fgts_to_provision }}"

    - name: DISCOVER AND ADD DEVICE FGT CLUSTER
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_username: "{{ item.device_username }}"
        device_password: "{{ item.device_password }}"
        device_ip: "{{ item.device_ip }}"
        device_unique_name: "{{ item.device_unique_name }}"
      tags:
        - discover_cluster
      with_items: "{{ var_fgt_clusters }}"