---

- name: CONFIG CUSTOM SERVICES
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  - name: ADD A CUSTOM SERVICE GROUP
    fmgr_fwobj_service:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      adom: "ansible"
      object_type: "group"
      group_name: "ansibleTestGroup"
      mode: "delete"