---

- name: CONFIG CUSTOM SERVICES
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  - name: ADD A CUSTOM SERVICE CATEGORY
    fmgr_fwobj_service:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      adom: "ansible"
      object_type: "category"
      comment: "created by ansible"
      category: "ansibleCategory5"
      mode: "set"