---
- name: "DELETE FAZ DEVICE"
  connection: local
  gather_facts: false
  hosts: FortiAnalyzer

  tasks:
    - name: DELETE VIRTUAL FORTIGATE
      faz_device:
        host: "{{inventory_hostname}}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "root"
        device_unique_name: "FGT01"
        state: "absent"