---
- name: CONFIGURE 3 FORTIGATES FROM SCRATCH INTO HA CLUSTER
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: DISCOVER AND ADD DEVICE FGT1
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.41"
        device_unique_name: "FGT1"
        device_serial: "FGVM010000122995"

    - name: DISCOVER AND ADD DEVICE FGT2
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.42"
        device_unique_name: "FGT2"
        device_serial: "FGVM010000123005"

    - name: DISCOVER AND ADD DEVICE FGT3
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.43"
        device_unique_name: "FGT3"
        device_serial: "FGVM010000123017"

    - name: CHANGE HOSTNAME FGT1
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        device_hostname: "ansible-fgt01"
        device_unique_name: "FGT1"
        adom: "ansible"


    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 1 FGT1
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT1"
        interface: "port10"
        interface_ip: "192.168.110.1/24"
        interface_allow_access: "ping, https"

    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 2 FGT1
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT1"
        interface: "port9"
        interface_ip: "192.168.109.1/24"
        interface_allow_access: "ping, https"

    - name: EDIT INTERFACE INFORMATION HA MGMT INTERFACE 5 FGT1
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT1"
        #interface to configure
        interface: "port2"
        #ip address to add to interface
        interface_ip: "10.7.220.151/25"
        #edit management access
        interface_allow_access: "ping, https"
        install_config: "enable"

    - name: CHANGE HOSTNAME FGT2
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        device_hostname: "ansible-fgt02"
        device_unique_name: "FGT2"
        adom: "ansible"

    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 1 FGT2
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT2"
        interface: "port10"
        interface_ip: "192.168.110.2/24"
        interface_allow_access: "ping, https"

    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 2 FGT2
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT2"
        interface: "port9"
        interface_ip: "192.168.109.2/24"
        interface_allow_access: "ping, https"

    - name: EDIT INTERFACE INFORMATION HA MGMT INTERFACE 5 FGT2 & INSTALL CONFIG
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT2"
        interface: "port2"
        interface_ip: "10.7.220.152/25"
        interface_allow_access: "ping, https"
        install_config: "enable"

    - name: CHANGE HOSTNAME FGT3
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        device_hostname: "ansible-fgt03"
        device_unique_name: "FGT3"
        adom: "ansible"

    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 1 FGT3
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT3"
        interface: "port10"
        interface_ip: "192.168.110.3/24"
        interface_allow_access: "ping, https"

    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 2 FGT3
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT3"
        interface: "port9"
        interface_ip: "192.168.109.3/24"
        interface_allow_access: "ping, https"

    - name: EDIT INTERFACE INFORMATION HA MGMT INTERFACE 5 FGT3 & INSTALL CONFIG
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT3"
        interface: "port2"
        interface_ip: "10.7.220.153/25"
        interface_allow_access: "ping, https"
        install_config: "enable"

    - pause:
        minutes: 1

    - name: CREATE SCRIPT FOR MASTER FGT01
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "device_ha_demo_master"
        script_type: "cli"
        script_target: "remote_device"
        script_description: "Create by Ansible"
        script_content: "config system ha \n
                          set group-id 10 \n
                          set group-name 'fgt-cluster' \n
                          set mode a-p \n
                          set password fortinet \n
                          set priority 203 \n
                          set hbdev port10 200 port9 100 \n
                          set authentication enable \n
                          set session-pickup enable \n
                          set session-pickup-connectionless enable \n
                          set override disable \n
                          set ha-mgmt-status enable \n
                          config ha-mgmt-interfaces \n
                            edit 1 \n
                              set interface port2 \n
                              end \n
                          end \n"

    - name: CREATE SCRIPT FOR SLAVE FGT02 & 3
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "device_ha_demo_slave"
        script_type: "cli"
        script_target: "remote_device"
        script_description: "Create by Ansible"
        script_content: "config system ha \n
                          set group-id 10 \n
                          set group-name 'fgt-cluster' \n
                          set mode a-p \n
                          set password fortinet \n
                          set priority 200 \n
                          set hbdev port10 200 port9 100 \n
                          set authentication enable \n
                          set session-pickup enable \n
                          set session-pickup-connectionless enable \n
                          set override disable \n
                          set ha-mgmt-status enable \n
                          config ha-mgmt-interfaces \n
                            edit 1 \n
                              set interface port2 \n
                              end \n
                          end \n"

    - name: EXECUTE SCRIPT ON FGT1
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "device_ha_demo_master"
        state: "execute"
        script_scope: "FGT1"

    - name: EXECUTE SCRIPT ON FGT2 & 3
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "device_ha_demo_slave"
        state: "execute"
        script_scope: "FGT2, FGT3"

    - pause:
        seconds: 15

    - name: DELETE FGT1
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT1"
        state: "absent"

    - name: DELETE FGT2
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT2"
        state: "absent"

    - name: DELETE FGT3
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT3"
        state: "absent"

    - name: DISCOVER AND ADD DEVICE FGT CLUSTER
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.41"
        device_unique_name: "FGT-cluster"