---
- name: DISCOVER AND ADD DEVICES
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: DISCOVER AND ADD DEVICE FGT1
      fmgr_device:
        #hard coded fortimanager example host and login -- see "fmg_group_add.yml for ansible host file version"
        host: "{{ inventory_hostname }}"
        #HARD CODED LOGIN FOR FORTIMANAGER SEE "fmg_group_add.yml" example for anisble host version
        username: "{{ username }}"
        password: "{{ password }}"
        #ADOM TO ADD THE DEVICE TO
        adom: "ansible"
        #DEVICE LOGIN
        device_username: "admin"
        device_password: "fortinet"
        #DEVICE IP ADDRESS
        device_ip: "10.7.220.41"
        #FRIENDLY NAME FOR DEVICE IN FORTIMANAGER
        device_unique_name: "FGT1"
        #SERIAL NUMBER OF DEVICE
        device_serial: "FGVM010000122995"
    - name: DISCOVER AND ADD DEVICE FGT2
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.42"
        device_unique_name: "FGT2"
        device_serial: "FGVM010000123005"
    - name: DISCOVER AND ADD DEVICE FGT3
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_username: "admin"
        device_password: "fortinet"
        device_ip: "10.7.220.43"
        device_unique_name: "FGT3"
        device_serial: "FGVM010000123017"
