---
- name: DISCOVER AND ADD DEVICES
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: SET HA SETTINGS
      fmgr_device_config:
        host: "{{inventory_hostname}}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "FGT1"
        ha_priority: "200"
        ha_mode: "AP"
        ha_group_name: "fgt-cluster-test"
        ha_authentication: "enable"
        ha_password: "fortinet"
        ha_group_id: "10"
        ha_hb_ports: "port10:200, port9:100"
        ha_session_pickup: "enable"
        ha_session_pickup_connectionless: "enable"
        ha_override: "disable"
