---
- name: CREATE AND EXECUTE SCRIPTS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: CREATE SCRIPT FOR MASTER FGT01
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "device_ha_demo_master"
        script_type: "cli"
        script_target: "remote_device"
        script_description: "Create by Ansible"
        script_content: "config system ha \n
                          set group-id 10 \n
                          set group-name 'fgt-cluster' \n
                          set mode a-p \n
                          set password fortinet \n
                          set priority 203 \n
                          set hbdev port10 200 port9 100 \n
                          set authentication enable \n
                          set session-pickup enable \n
                          set session-pickup-connectionless enable \n
                          set override disable \n
                          end \n"

    - name: CREATE SCRIPT FOR SLAVE FGT02 & 3
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "device_ha_demo_slave"
        script_type: "cli"
        script_target: "remote_device"
        script_description: "Create by Ansible"
        script_content: "config system ha \n
                          set group-id 10 \n
                          set group-name 'fgt-cluster' \n
                          set mode a-p \n
                          set password fortinet \n
                          set priority 200 \n
                          set hbdev port10 200 port9 100 \n
                          set authentication enable \n
                          set session-pickup enable \n
                          set session-pickup-connectionless enable \n
                          set override disable \n
                          end \n"