---
- name: "SET FORTIMETER LIC LEVEL"
  connection: local
  gather_facts: false
  hosts: FortiManager

  tasks:
#    - name: SET LICENSING MODE ON FORTIMETER DEVICE to ALL
#      fmgr_fortimeter:
#        host: "{{inventory_hostname}}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "ansible"
#        device_unique_name: "seattle-fgt-cluster"
#        fortimeter_utm_level: "all"

    - name: SET LICENSING MODE ON FORTIMETER DEVICE to a COMBO
      fmgr_fortimeter:
        host: "{{inventory_hostname}}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        device_unique_name: "nyc-fgt-cluster"
        fortimeter_utm_level: "fw, ips, av"

