---
- name: "SET FORTIMETER LIC LEVEL"
  connection: local
  gather_facts: false
  hosts: FortiProvision

  tasks:
    - name: SET LICENSING MODE ON FORTIMETER DEVICE to a COMBO
      fmgr_fortimeter:
        host: "{{inventory_hostname}}"
        username: "fortiprovision"
        password: "fortiprovision"
        adom: "root"
        device_unique_name: "FOSVM1FGPRJ411DD"
        fortimeter_utm_level: "fw, ips, av, ac, all"
        foslic_type: 2

