---

- name: CREATE FGT GRP
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:

  - name: CREATE DEVICE GROUP
    fmgr_device_group:
      #GETTING FORTIMANAGER HOST IP OR NAME FROM ANSIBLE INVENTORY FOR HOSTS GROUP ABOVE
      host: "{{ inventory_hostname }}"
      #DYNAMIC MAPPING FOR THE FORTIMANAGER LOGIN AS SPECIFIED IN INVENTORY FILE
      username: "{{ username }}"
      password: "{{ password }}"
      #NAME OF GROUP YOU WANT TO ADD
      grp_name: "TestGroup"
      #DESCRIPTION TO ADD TO GROUP
      grp_desc: "CreatedbyAnsible"
      #ADOM TO CREATE THE GROUP IN
      adom: "ansible"
      #STATE if "present" add the group, if "absent" delete the GROUP
      state: "present"

  - name: CREATE DEVICE GROUP2
    fmgr_device_group:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      grp_name: "testtest"
      grp_desc: "CreatedbyAnsible"
      adom: "ansible"
      state: "present"
