---
- name: CREATE DEVICE GROUP AND ADD MEMBERS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: CREATE DEVICE GROUP
      fmgr_device_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        grp_name: "TestGroup"
        grp_desc: "CreatedbyAnsible"
        adom: "ansible"

    - name: CREATE DEVICE GROUP
      fmgr_device_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        grp_name: "AnsibleGroup"
        grp_desc: "CreatedbyAnsible"
        adom: "ansible"

    - name: ADD DEVICES TO DEVICE GROUP
      fmgr_device_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        grp_name: "TestGroup"
        grp_members: "FGT1,FGT2"
        adom: "ansible"

    - name: DELETE DEVICE GROUP
      fmgr_device_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        grp_name: "AnsibleGroup"
        grp_desc: "CreatedbyAnsible"
        state: "absent"
        adom: "ansible"
