---

- name: REMOVE DEVICES FROM FGT GRP
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: REMOVE DEVICES FROM DEVICE GROUP
      fmgr_device_group:
        #GETTING FORTIMANAGER HOST IP OR NAME FROM ANSIBLE INVENTORY FOR HOSTS GROUP ABOVE
        host: "{{ inventory_hostname }}"
        #DYNAMIC MAPPING FOR THE FORTIMANAGER LOGIN AS SPECIFIED IN INVENTORY FILE
        username: "{{ username }}"
        password: "{{ password }}"
        #STATE if "present" ADD THE GROUP MEMBERS, IF "absent" DELETE THE GROUP MEMBERS
        state: "absent"
        #GROUP NAME TO REMOVE THE DEVICES FROM
        grp_name: "testtest"
        #FRIENDLY NAME OF DEVICES IN FORTIMANAGER YOU WISH TO DELETE FROM THE GROUP
        #MULTIPLE DEVICES CAN BE SPECIFIED BY COMMA SEPARATION (CSV)
        grp_members: "FGT3"
        #ADOM YOU WISH TO ADD
        adom: "ansible"

    - name: REMOVE DEVICES FROM DEVICE GROUP2
      fmgr_device_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "absent"
        grp_name: "TestGroup"
        grp_members: "FGT1,FGT2"
        adom: "ansible"
