---
- name: CONFIGURE 3 FORTIGATES FROM SCRATCH INTO HA CLUSTER
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: DISCOVER AND ADD DEVICES VIA LOOP
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_username: "{{ item.device_username }}"
        device_password: "{{ item.device_password }}"
        device_ip: "{{ item.device_ip }}"
        device_unique_name: "{{ item.device_unique_name }}"
      loop:
        - device_unique_name: "FGT1"
          device_username: "admin"
          device_password: "fortinet"
          device_ip: "10.7.220.41"
        - device_unique_name: "FGT2"
          device_username: "admin"
          device_password: "fortinet"
          device_ip: "10.7.220.42"
        - device_unique_name: "FGT3"
          device_username: "admin"
          device_password: "fortinet"
          device_ip: "10.7.220.43"
      loop_control:
        label: "{{ item.device_unique_name }}"

#    - name: CHANGE HOSTNAMES VIA LOOP
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        device_hostname: "{{ item.device_hostname }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        adom: "{{ item.adom }}"
#
#    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 1 FGT1
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "{{ item.intf.name }}"
#        interface_ip: "{{ item.intf.ip }}"
#        interface_allow_access: "ping, https"
#
#    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 2 FGT1
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port9"
#        interface_ip: "192.168.109.1/24"
#        interface_allow_access: "ping, https"
#
#    - name: EDIT INTERFACE INFORMATION HA MGMT INTERFACE 5 FGT1
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port2"
#        interface_ip: "10.7.220.151/25"
#        interface_allow_access: "ping, https"
#        install_config: "enable"
#
#    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 1 FGT2
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port10"
#        interface_ip: "192.168.110.2/24"
#        interface_allow_access: "ping, https"
#
#    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 2 FGT2
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port9"
#        interface_ip: "192.168.109.2/24"
#        interface_allow_access: "ping, https"
#
#    - name: EDIT INTERFACE INFORMATION HA MGMT INTERFACE 5 FGT2 & INSTALL CONFIG
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port2"
#        interface_ip: "10.7.220.152/25"
#        interface_allow_access: "ping, https"
#        install_config: "enable"
#
#    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 1 FGT3
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port10"
#        interface_ip: "192.168.110.3/24"
#        interface_allow_access: "ping, https"
#
#    - name: EDIT INTERFACE INFORMATION HA HEARTBEAT 2 FGT3
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port9"
#        interface_ip: "192.168.109.3/24"
#        interface_allow_access: "ping, https"
#
#    - name: EDIT INTERFACE INFORMATION HA MGMT INTERFACE 5 FGT3 & INSTALL CONFIG
#      fmgr_device_config:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        interface: "port2"
#        interface_ip: "10.7.220.153/25"
#        interface_allow_access: "ping, https"
#        install_config: "enable"
#
#    - pause:
#        minutes: 1
#
#    - name: CREATE SCRIPT FOR MASTER FGT01
#      fmgr_script:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        script_name: "device_ha_demo_master"
#        script_type: "cli"
#        script_target: "remote_device"
#        script_description: "Create by Ansible"
#        script_content: "config system ha \n
#                          set group-id 10 \n
#                          set group-name 'fgt-cluster' \n
#                          set mode a-p \n
#                          set password fortinet \n
#                          set priority 203 \n
#                          set hbdev port10 200 port9 100 \n
#                          set authentication enable \n
#                          set session-pickup enable \n
#                          set session-pickup-connectionless enable \n
#                          set override disable \n
#                          set ha-mgmt-status enable \n
#                          config ha-mgmt-interfaces \n
#                            edit 1 \n
#                              set interface port2 \n
#                              end \n
#                          end \n"
#
#    - name: CREATE SCRIPT FOR SLAVE FGT02 & 3
#      fmgr_script:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        script_name: "device_ha_demo_slave"
#        script_type: "cli"
#        script_target: "remote_device"
#        script_description: "Create by Ansible"
#        script_content: "config system ha \n
#                          set group-id 10 \n
#                          set group-name 'fgt-cluster' \n
#                          set mode a-p \n
#                          set password fortinet \n
#                          set priority 200 \n
#                          set hbdev port10 200 port9 100 \n
#                          set authentication enable \n
#                          set session-pickup enable \n
#                          set session-pickup-connectionless enable \n
#                          set override disable \n
#                          set ha-mgmt-status enable \n
#                          config ha-mgmt-interfaces \n
#                            edit 1 \n
#                              set interface port2 \n
#                              end \n
#                          end \n"
#
#    - name: EXECUTE SCRIPT ON FGT1
#      fmgr_script:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        script_name: "device_ha_demo_master"
#        state: "execute"
#        script_scope: "FGT1"
#
#    - name: EXECUTE SCRIPT ON FGT2 & 3
#      fmgr_script:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        script_name: "device_ha_demo_slave"
#        state: "execute"
#        script_scope: "FGT2, FGT3"
#
#    - pause:
#        seconds: 15
#
#    - name: DELETE SINGLE FORTIGATES FROM FORTIANALYZER
#      fmgr_device:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_unique_name: "{{ item.device_unique_name }}"
#        state: "absent"
#
#    - name: DISCOVER AND ADD DEVICE FGT CLUSTER
#      fmgr_device:
#        host: "{{ inventory_hostname }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        adom: "{{ item.adom }}"
#        device_username: "{{ item.device_username }}"
#        device_username: "{{ item.device_password }}"
#        device_ip: "{{ item.device_ip }}"
#        device_unique_name: "FGT-cluster"