---
- name: CONFIGURE 3 FORTIGATES FROM SCRATCH INTO HA CLUSTER
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: DISCOVER AND ADD DEVICES VIA LOOP
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_username: "{{ item.device_username }}"
        device_password: "{{ item.device_password }}"
        device_ip: "{{ item.device_ip }}"
        device_unique_name: "{{ item.device_unique_name }}"
      tags:
        - discover
      with_items:
        - { device_unique_name: "FGT1",
              device_username: "admin",
              device_password: "fortinet",
              device_ip: "10.7.220.41",
              adom: "ansible" }
        - { device_unique_name: "FGT2",
              device_username: "admin",
              device_password: "fortinet",
              device_ip: "10.7.220.42",
              adom: "ansible" }
        - { device_unique_name: "FGT3",
              device_username: "admin",
              device_password: "fortinet",
               device_ip: "10.7.220.43",
               adom: "ansible" }

    - name: CHANGE HOSTNAMES VIA LOOP
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        device_hostname: "{{ item.device_hostname }}"
        device_unique_name: "{{ item.device_unique_name }}"
        adom: "{{ item.adom }}"
      tags:
        - hostname
      with_items:
        - { device_unique_name: "FGT1", device_hostname: "ansible-fgt01", adom: "ansible" }
        - { device_unique_name: "FGT2", device_hostname: "ansible-fgt02", adom: "ansible" }
        - { device_unique_name: "FGT3", device_hostname: "ansible-fgt03", adom: "ansible" }

    - name: EDIT INTERFACE INFORMATION ON FORTIGATES
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_unique_name: "{{ item.device_unique_name }}"
        interface: "{{ item.interface }}"
        interface_ip: "{{ item.interface_ip }}"
        interface_allow_access: "ping, https"
      tags:
        - interface
      with_items:
        - { device_unique_name: "FGT1", adom: "ansible", interface: "port10", interface_ip: "192.168.110.1/24" }
        - { device_unique_name: "FGT1", adom: "ansible", interface: "port9", interface_ip: "192.168.109.1/24" }
        - { device_unique_name: "FGT1", adom: "ansible", interface: "port2", interface_ip: "10.7.220.151/25" }
        - { device_unique_name: "FGT2", adom: "ansible", interface: "port10", interface_ip: "192.168.110.2/24" }
        - { device_unique_name: "FGT2", adom: "ansible", interface: "port9", interface_ip: "192.168.109.2/24" }
        - { device_unique_name: "FGT2", adom: "ansible", interface: "port2", interface_ip: "10.7.220.152/25" }
        - { device_unique_name: "FGT3", adom: "ansible", interface: "port10", interface_ip: "192.168.110.3/24" }
        - { device_unique_name: "FGT3", adom: "ansible", interface: "port9", interface_ip: "192.168.109.3/24" }
        - { device_unique_name: "FGT3", adom: "ansible", interface: "port2", interface_ip: "10.7.220.153/25" }

    - name: INSTALL NEW CONFIGS TO FORTIGATES
      fmgr_device_config:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_unique_name: "{{ item.device_unique_name }}"
        install_config: "enable"
      tags:
        - config_install
      with_items:
        - { device_unique_name: "FGT1",
              adom: "ansible" }
        - { device_unique_name: "FGT2",
              adom: "ansible" }
        - { device_unique_name: "FGT3",
              adom: "ansible" }

    - pause:
        seconds: 30

    - name: CREATE SCRIPT FOR CLUSTER INIT
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        script_name: "{{ item.script_name }}"
        script_type: "{{ item.script_type }}"
        script_target: "{{ item.script_target }}"
        script_description: "{{ item.script_description }}"
        script_content: "{{ item.script_content }}"
      tags:
        - create_script
      with_items:
        - { adom: "ansible",
            script_name: "fgt_ha_group10",
            script_type: "cli",
            script_target: "remote_device",
            script_description: "HA SCRIPT FOR GROUP 10",
            script_content: "config system ha \n
                          set group-id 10 \n
                          set group-name 'fgt-cluster' \n
                          set mode a-p \n
                          set password fortinet \n
                          set priority 200 \n
                          set hbdev port10 200 port9 100 \n
                          set authentication enable \n
                          set session-pickup enable \n
                          set session-pickup-connectionless enable \n
                          set override disable \n
                          set ha-mgmt-status enable \n
                          config ha-mgmt-interfaces \n
                            edit 1 \n
                              set interface port1 \n
                              set gateway 10.7.220.126
                              set dst 0.0.0.0
                              end \n
                          end \n"}

    - name: EXECUTE SCRIPT ON FORTIGATES
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        script_name: "{{ item.script_name }}"
        state: "execute"
        script_scope: "{{ item.script_scope }}"
      tags:
        - exec_script
      with_items:
        - { adom: "ansible",
              script_name: "fgt_ha_group10",
              script_scope: "FGT1, FGT2, FGT3"}

    - pause:
        seconds: 15

    - name: DELETE SINGLE FORTIGATES FROM FORTIANALYZER
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_unique_name: "{{ item.device_unique_name }}"
        state: "absent"
      tags:
        - delete_fgts
      with_items:
        - { device_unique_name: "FGT1", adom: "ansible" }
        - { device_unique_name: "FGT2", adom: "ansible" }
        - { device_unique_name: "FGT3", adom: "ansible" }

    - name: DISCOVER AND ADD DEVICE FGT CLUSTER
      fmgr_device:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "{{ item.adom }}"
        device_username: "{{ item.device_username }}"
        device_password: "{{ item.device_password }}"
        device_ip: "{{ item.device_ip }}"
        device_unique_name: "{{ item.device_unique_name }}"
      tags:
        - discover_cluster
      with_items:
        - { device_unique_name: "fgt-cluster",
              device_username: "admin",
              device_password: "fortinet",
              device_ip: "10.7.220.43",
              adom: "ansible" }