fortigates:
  - { device_unique_name: "FGT1",
        device_username: "admin",
        device_password: "fortinet",
        device_ip: "10.7.220.41",
        adom: "ansible"}
  - { device_unique_name: "FGT2",
        device_username: "admin",
        device_password: "fortinet",
        device_ip: "10.7.220.42",
        adom: "ansible" }
  - { device_unique_name: "FGT3",
        device_username: "admin",
        device_password: "fortinet",
        device_ip: "10.7.220.43",
        adom: "ansible" }