---

- name: CONFIG FW POLICY PACKAGES AND FOLDERS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
  - name: USE CUSTOM TYPE TO QUERY AVAILABLE SCRIPTS
    fmgr_query:
      host: "{{inventory_hostname}}"
      username: "{{ username }}"
      password: "{{ password }}"
      adom: "ansible"
      object: "custom"
      custom_endpoint: "/pm/pkg/adom/ansible"


