---
- name: CREATE AND EXECUTE SCRIPTS
  hosts: FortiManager
  connection: local
  gather_facts: False

  tasks:
    - name: EXECUTE SCRIPT
      fmgr_script:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "ansible"
        script_name: "device_ha_demo"
        state: "execute"
        script_scope: "FGT1, FGT2, FGT3"

